#!/bin/bash -ex
## Install and create Bosh lite under vbox

# source for these steps: http://bosh.io/docs/bosh-lite.html
#clone bosh-deployment
#TODO: add check to see if it already exists
git clone https://github.com/cloudfoundry/bosh-deployment ~/workspace/bosh-deployment

#set up your workspace
#TODO: add check to see if it already exists
mkdir -p ~/workspace/deployments/vbox


#edit deployment manifest
#TODO: Raise ram
#TODO: raise disk
#TODO: Raise CPUs

#create bosh director
bosh create-env ~/workspace/bosh-deployment/bosh.yml \
  --state ~/workspace/deployments/vbox/state.json \
  -o ~/workspace/bosh-deployment/virtualbox/cpi.yml \
  -o ~/workspace/bosh-deployment/virtualbox/outbound-network.yml \
  -o ~/workspace/bosh-deployment/bosh-lite.yml \
  -o ~/workspace/bosh-deployment/bosh-lite-runc.yml \
  -o ~/workspace/bosh-deployment/jumpbox-user.yml \
  --vars-store  ~/workspace/deployments/vbox/creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork

#Set bosh log-in info
bosh alias-env vbox -e 192.168.50.6 --ca-cert <(bosh int  ~/workspace/deployments/vbox/creds.yml --path /director_ssl/ca)
export BOSH_CLIENT=admin
export BOSH_CLIENT_SECRET=`bosh int ~/workspace/deployments/vbox/creds.yml --path /admin_password`


#confirm works
bosh -e vbox env

##Deploy cf-deployment
#source for these steps(https://github.com/cloudfoundry/cf-deployment#deploying-cf)
#TODO: add check to see if it already exists
git clone https://github.com/cloudfoundry/cf-deployment ~/workspace/deployments/vbox/cf-deployment

#edit deployment manifest 
#reduce intsance counts to 1
sed -i ''  's/instances: [0-9]/instances: 1/'  ~/workspace/deployments/vbox/cf-deployment/cf-deployment.yml 
#reduce disk sizes
#reduce memory sizes

#configure cloud config (this file need to be tweaked)
bosh -e vbox update-cloud-config ~/workspace/deployments/vbox/cf-deployment/bosh-lite/cloud-config.yml -n


bosh -e vbox upload-stemcell https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-trusty-go_agent


#deploy that shit
bosh -e vbox -d cf deploy ~/workspace/deployments/vbox/cf-deployment/cf-deployment.yml \
  -o   ~/workspace/deployments/vbox/cf-deployment/operations/bosh-lite.yml \
  --vars-store   ~/workspace/deployments/vbox/cf-deployment/deployment-vars.yml \
  -v system_domain=bosh-lite.com \
  --recreate \
  --fix \
  -n

#run smoketests

#set env vars for cf logins
bosh int deployment-vars.yml  --path /cf_admin_password

